### PR TITLE
Fix for #51 Wrong result of JsDiff.diffLines

### PR DESCRIPTION
**Pull request by felicienfrancois**
Need to be checked as I don't know what is the expected behavior for TrimmedLineDiff.

### CODE REVIEW

**Comment by kpdecker** [comment]
Can you add a test case to cover this failure?

**Comment by felicienfrancois** [comment]
Done

**Comment by kpdecker** [comment]
Thanks!

**Comment by kpdecker** [comment]
Released in 1.3.1

**Comment by Dzenly** [comment]
Seems like there remains the bug when empty line after a change:
https://github.com/kpdecker/jsdiff/issues/235

**Pull request merged**
