### PR TITLE
Threat each newline as separate word in `diffWordsWithSpace`

### LINKED ISSUE #180: diffWordsWithSpace - a char-by-char diff for spaces?
```js
require('diff').convertChangesToXML(
  require('diff').diffWordsWithSpace('foo\nbar', 'foo\n\n\nbar')
)
```

Returns:

```js
'foo<del>\n</del><ins>\n\n\n</ins>bar'
```

Desired output is:

```js
'foo<ins>\n\n</ins>bar'
```

As far as I understand, `diffWordsWithSpace` currently treats any amount of spaces as a single token. Which makes sense for `diffWords` (where space isn't significant), but doesn't work well for `diffWordsWithSpace`.

Suggestion: maybe it should compare spaces between words on character-by-character basis?

Possible solution - change regexp in [tokenizer](https://github.com/kpdecker/jsdiff/blob/8f8e0f296a6935a1854d1f2c0ea7ddac7e89a0ae/src/diff/word.js#L35) like this:

```diff
<   let tokens = value.split(/(\s+|\b)/);
---
>   let tokens = this.options.ignoreWhitespace ?
>                value.split(/(\s+|\b)/) :
>                value.split(/(\s|\b)/);
```

Seems to work fine for me, but I'm not quite sure it's correct.

### PR DESCRIPTION
**Pull request by Mingun**
This fixes #180 & #211

### CODE REVIEW

**Comment by Mingun** [comment]
@kpdecker any feedback?

**Comment by h2grover** [comment]
@Mingun how soon this fix will be merged?

**Comment by Mingun** [comment]
@kpdecker, can we make progress with this? Better late than never

**Comment by kpdecker** [comment]
Sorry for the delay on this, Have very few cycles for this project these days.

**Comment by Mingun** [comment]
Nice to see that you don't forgot the project

**Comment by ExplodingCabbage** [comment]
IMO the behaviour this produces for `diffWords` is broken as a result of the extra tokens. Here's a diff using the code _before_ this change...

```
> wd.diffWords("foo bar", "foo\n\nbar")
[ { value: 'foo\n\nbar', count: 3 } ]
```

... and here's one with the code _after_ this change:

```
> wd.diffWords("foo bar", "foo\n\nbar")
[
  { count: 2, value: 'foo\n' },
  { count: 1, added: true, removed: undefined, value: '\n' },
  { count: 1, value: 'bar' }
]
```

We're now only *sort-of-ignoring* whitespace in `diffWords`.

(In fairness, we were already doing a bad job of ignoring whitespace in `diffWords`; if you changed the whitespace around some *punctuation* it would be treated as a change, before.)

**Pull request merged**
